### ISSUE TITLE
Address  Book crash

### ISSUE THREAD

**Issue by pixyish** [Alterplay/APAddressBook#77]
When following these step

1. run app
2. go to setting-> privacy->contact-> AddressBook->
Turn off the contact access service it crash.

Please solve this ASAP

**Comment by Krivoblotsky** [comment]
This is expected behavior. iOS kills applications that react permissions changes. Actually its not a crash, the system sends SIGKILL signal.
http://stackoverflow.com/questions/12522574/toggling-privacy-settings-will-kill-the-app
http://stackoverflow.com/questions/12810638/app-crashed-in-ios-6-when-user-changes-contacts-access-permissions
